### ISSUE TITLE
KeyError: 'storageSize'

### ISSUE THREAD

**Issue by gleidsonlm** [zerausolrac/PyCollab#3]
Hi!

Thanks for the script, I'm receiving this error when trying to execute a medium set of courses (>500) with 1 (one) week of recordings parameter:

```
Traceback (most recent call last):
  File "Collab.py", line 26, in <module>
    grabaciones = ut.listaGrabaciones(grabacionesJson)
  File "/usr/local/opt/PyCollab/Utilidades.py", line 18, in listaGrabaciones
    recordinglist.append({"recording_id" : recordings['results'][x]['id'], "recording_name" : recordings['results'][x]['name'], "duration":recordings['results'][x]['duration'], "storageSize":recordings['results'][x]['storageSize'],"created": recordings['results'][x]['created']})
KeyError: 'storageSize'

```

Thanks for any assistance =D

**Comment by zerausolrac** [comment]
that 'storageSize' value depends of Blackboard API response, it is not presented on all recording as value , I fixed this on new release of script
